[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

; Real Adafruit driver (pulls in Adafruit BusIO + Wire automatically)
lib_deps =
    adafruit/Adafruit INA219@^1.2.0

upload_protocol = arduino
upload_speed = 115200
monitor_speed = 115200
